import { Header, Page } from "@/components";

import { AuthProvider } from "@/providers/AuthContext";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <AuthProvider>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          <Header />
          <Page>{children}</Page>
        </body>
      </AuthProvider>
    </html>
  );
}
